language: generic
dist: trusty
services: docker
sudo: false
matrix:
  include:
    - name: x86_64-linux
    - name: aarch64-linux
      sudo: required
      env:
        - GOGUT_INSTALL_DEPS=1
      install: make
      script: make test
  allow_failures:
    - name: aarch64-linux
  fast_finish: true
before_script:
  # Show environment.
  - uname -a
  - id
  - pwd
script:
  - ./sample_test.sh
